// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaMkDpc1wmRHae9lSsS_a9L1rHHxI-tuQ',
    appId: '1:548701644720:android:1a0639c52a552f01c6d875',
    messagingSenderId: '548701644720',
    projectId: 'raufastore-5e03e',
    storageBucket: 'raufastore-5e03e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCFstwMYQiUXNEdFkiqkah5yLyjHPiL0M',
    appId: '1:548701644720:ios:621d39761fca2fbec6d875',
    messagingSenderId: '548701644720',
    projectId: 'raufastore-5e03e',
    storageBucket: 'raufastore-5e03e.appspot.com',
    androidClientId: '548701644720-annmdg4p27pqn2535m7eh46tsdge5vnt.apps.googleusercontent.com',
    iosClientId: '548701644720-ekhq811srqkdmqog4cm595ohduo3vq74.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessangerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCFstwMYQiUXNEdFkiqkah5yLyjHPiL0M',
    appId: '1:548701644720:ios:b196bb17183eeeb6c6d875',
    messagingSenderId: '548701644720',
    projectId: 'raufastore-5e03e',
    storageBucket: 'raufastore-5e03e.appspot.com',
    androidClientId: '548701644720-annmdg4p27pqn2535m7eh46tsdge5vnt.apps.googleusercontent.com',
    iosClientId: '548701644720-e3pcebm1idh8124l4o155uefhjfivhhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessangerApp.RunnerTests',
  );
}
